add name to metadata so it works with Policyfiles
otherwise:

```
$ chef install
Building policy mancave
Expanded run list: recipe[users], recipe[deployer]
Caching Cookbooks...
Installing users    4.0.3
Installing deployer 0.1.1
Installing sudo     3.1.0
Error: Failed to generate Policyfile.lock
Reason: (Chef::Exceptions::MetadataNotValid) Cookbook loaded at path(s) [/home/artm/.chefdk/cache/cookbooks/deployer-0.1.1-supermarket.chef.io] has invalid metadata: The `name' attribute is required in cookbook metadata
```